dist: xenial

language:
  - php
  - node_js

php:
  - "5.6"
  - "7.0"
  - "7.2"
  - "7.3"

addons:
  apt:
    packages:
      # For xmllint.
      - libxml2-utils
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

services:
  - mysql

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - export DEV_LIB_ONLY="phpunit"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run lint
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm run release

deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  file: stream.zip
  on:
    tags: true

# Pull requests are built by default.
branches:
  only:
  - master
  - develop

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
