dist: xenial

language: php

php:
  - "5.6"
  - "7.2"
  - "7.3"
  - "7.4"

jobs:
  include:
    - name: Release Package
      php: "7.4"
      env: WP_RELEASE=1

services:
  - docker

before_install:
  - docker load -i /tmp/docker_images/images.tar || true
  - nvm install
  - nvm use

install:
  - npm install

script:
  - npm run lint
  - npm run phpunit
  - npm run phpunit-multisite

after_script:
  - test -f ./tests/reports/clover.xml && composer test-report || true

before_deploy:
  - npm run release

before_cache:
  - docker save -o /tmp/docker_images/images.tar $(docker images -a -q)

deploy:
  provider: releases
  api_key:
    secure: HheYiv6c8ipHzMZBTH7xcKrOwCllvJTtfiTffAPK6XubWe3Kudn6IJUv0p1gmRhWXxZ5ciJQ/sgiCRGTRm/bubHs4tS7JOmpmoTdkrXajTxyyDCKpxhtT43nie0vNF+pWqVu2yOjhDR4pwtWjpQdzEKOz0kn0XSMT+vGsKQD50w=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - stream.zip
    - stream-$TRAVIS_TAG.zip
  on:
    tags: true
    condition: "$WP_RELEASE = 1"

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
    - /tmp/docker_images
