dist: xenial

language: php

php:
  - "5.6"
  - "7.0"
  - "7.2"
  - "7.3"

services:
  - mysql

addons:
  apt:
    packages:
      # For xmllint.
      - libxml2-utils
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

jobs:
  include:
    - name: Release Package
      php: "7.3"
      env: WP_VERSION=latest WP_MULTISITE=0
      deploy:
        # Publish a release to the distribution repository.
        - provider: script
          script: bash local/scripts/dist.sh
          skip_cleanup: true
          on:
            repo: xwp/stream
            tags: true
            all_branches: true
        # Upload a release to a tag here as well.
        - provider: releases
          api_key:
            secure: HheYiv6c8ipHzMZBTH7xcKrOwCllvJTtfiTffAPK6XubWe3Kudn6IJUv0p1gmRhWXxZ5ciJQ/sgiCRGTRm/bubHs4tS7JOmpmoTdkrXajTxyyDCKpxhtT43nie0vNF+pWqVu2yOjhDR4pwtWjpQdzEKOz0kn0XSMT+vGsKQD50w=
          skip_cleanup: true
          file:
            - stream.zip
            - stream-$TRAVIS_TAG.zip
          on:
            repo: xwp/stream
            tags: true

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - export DEV_LIB_ONLY="phpunit"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run lint
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm run release

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
