dist: xenial

language: php

php:
  - "5.6"
  - "7.0"
  - "7.2"
  - "7.3"

addons:
  apt:
    packages:
      # For xmllint.
      - libxml2-utils
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

jobs:
  include:
    - name: Release Package
      php: "7.3"
      env: WP_VERSION=latest WP_MULTISITE=0
      deploy:
        # Publish a release.
        - provider: script
          script: bash local/scripts/dist.sh "$TRAVIS_TAG"
          on:
            tags: true
        # Publish a working branch.
        - provider: script
          script: bash local/scripts/dist.sh
          on:
            all_branches: true

services:
  - mysql

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - export DEV_LIB_ONLY="phpunit"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run lint
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - npm run release

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
